<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    DB::table('countries')->truncate(); 

    $countries = [
        ['name' => 'Afghanistan', 'code' => 'AF', 'telephonecode' => '+ 93', 'continent_id' =>  2],
        ['name' => 'Åland Islands', 'code' => 'AX', 'telephonecode' => '+ 358','continent_id' => 3],
        ['name' => 'Albania', 'code' => 'AL', 'telephonecode' => '+ 355','continent_id' => 3],
        ['name' => 'Algeria', 'code' => 'DZ', 'telephonecode' => '+ 213','continent_id' => 1],
        ['name' => 'American Samoa', 'code' => 'AS', 'telephonecode' => '+ 1-684','continent_id' => 5],
        ['name' => 'Andorra', 'code' => 'AD', 'telephonecode' => '+ 376','continent_id' => 3],
        ['name' => 'Angola', 'code' => 'AO', 'telephonecode' => '+ 244','continent_id' => 1],
        ['name' => 'Anguilla', 'code' => 'AI', 'telephonecode' => '+ 1-264','continent_id' => 4],
        ['name' => 'Antarctica', 'code' => 'AQ', 'telephonecode' => '+ 672','continent_id' => 5],
        ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'telephonecode' => '+ 1-268','continent_id' => 4],
        ['name' => 'Argentina', 'code' => 'AR', 'telephonecode' => '+ 54','continent_id' => 6],
        ['name' => 'Armenia', 'code' => 'AM', 'telephonecode' => '+ 374','continent_id' => 2],
        ['name' => 'Aruba', 'code' => 'AW', 'telephonecode' => '+ 297','continent_id' => 6],
        ['name' => 'Australia', 'code' => 'AU', 'telephonecode' => '+ 61','continent_id' => 5],
        ['name' => 'Austria', 'code' => 'AT', 'telephonecode' => '+ 43','continent_id' => 3],
        ['name' => 'Azerbaijan', 'code' => 'AZ', 'telephonecode' => '+ 994','continent_id' => 3],
        ['name' => 'Bahamas', 'code' => 'BS', 'telephonecode' => '+ 1-242','continent_id' => 4],
        ['name' => 'Bahrain', 'code' => 'BH', 'telephonecode' => '+ 973','continent_id' => 2],
        ['name' => 'Bangladesh', 'code' => 'BD', 'telephonecode' => '+ 880','continent_id' => 2],
        ['name' => 'Barbados', 'code' => 'BB', 'telephonecode' => '+ 1-246','continent_id' => 4],
        ['name' => 'Belarus', 'code' => 'BY', 'telephonecode' => '+ 375','contient_id' => 3],
        ['name' => 'Belgium', 'code' => 'BE', 'telephonecode' => '+ 32','continent_id' => 3],
        ['name' => 'Belize', 'code' => 'BZ', 'telephonecode' => '+ 501','continent_id' => 4],
        ['name' => 'Benin', 'code' => 'BJ', 'telephonecode' => '+ 229','continent_id' => 1],
        ['name' => 'Bermuda', 'code' => 'BM', 'telephonecode' => '+ 1-441','continent_id' => 4],
        ['name' => 'Bhutan', 'code' => 'BT', 'telephonecode' => '+ 975','continent_id' => 2],
        ['name' => 'Bolivia', 'code' => 'BO', 'telephonecode' => '+ 591','continent_id' => 6],
        ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'telephonecode' => '+ 599','continent_id' => 6],
        ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'telephonecode' => '+ 387','continent_id' => 3],
        ['name' => 'Botswana', 'code' => 'BW', 'telephonecode' => '+ 267','continent_id' => 1],
        ['name' => 'Bouvet Island', 'code' => 'BV', 'telephonecode' => '+ 47','continent_id' => 3],
        ['name' => 'Brazil', 'code' => 'BR', 'telephonecode' => '+ 55','continent_id' => 6],
        ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'telephonecode' => '+ 246','continent_id' => 2],
        ['name' => 'British Virgin Islands', 'code' => 'VG', 'telephonecode' => '+ 1-284','continent_id' => 4],
        ['name' => 'Brunei Darussalam', 'code' => 'BN', 'telephonecode' => '+ 673','continent_id' => 2],
        ['name' => 'Bulgaria', 'code' => 'BG', 'telephonecode' => '+ 359','continent_id' => 3],
        ['name' => 'Burkina Faso', 'code' => 'BF', 'telephonecode' => '+ 226','continent_id' => 1],
        ['name' => 'Burundi', 'code' => 'BI', 'telephonecode' => '+ 257','continent_id' => 1],
        ['name' => 'Cambodia', 'code' => 'KH', 'telephonecode' => '+ 855','continent_id' => 1],
        ['name' => 'Cameroon', 'code' => 'CM', 'telephonecode' => '+ 237','continent_id' => 1],
        ['name' => 'Canada', 'code' => 'CA', 'telephonecode' => '+ 1','continent_id' => 4],
        ['name' => 'Cape Verde', 'code' => 'CV', 'telephonecode' => '+ 238','continent_id' => 1],
        ['name' => 'Cayman Islands', 'code' => 'KY', 'telephonecode' => '+ 1-345','continent_id' => 4],
        ['name' => 'Central African Republic', 'code' => 'CF', 'telephonecode' => '+ 236','continent_id' => 1],
        ['name' => 'Chad', 'code' => 'TD', 'telephonecode' => '+ 235','continent_id' => 1],
        ['name' => 'Chile', 'code' => 'CL', 'telephonecode' => '+ 56','continent_id' => 6],
        ['name' => 'China', 'code' => 'CN', 'telephonecode' => '+ 86','continent_id' => 2],
        ['name' => 'Christmas Island', 'code' => 'CX', 'telephonecode' => '+ 61','continent_id' => 5],
        ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'telephonecode' => '+ 61','continent_id' => 5],
        ['name' => 'Colombia', 'code' => 'CO', 'telephonecode' => '+ 57','continent_id' => 6],
        ['name' => 'Comoros', 'code' => 'KM', 'telephonecode' => '+ 269','continent_id' => 1],
        ['name' => 'Congo', 'code' => 'CG', 'telephonecode' => '+ 242','continent_id' => 1],
        ['name' => 'Congo Democratic Republic', 'code' => 'CD', 'telephonecode' => '+ 243','continent_id' => 1],
        ['name' => 'Cook Islands', 'code' => 'CK', 'telephonecode' => '+ 682','continent_id' => 5],
        ['name' => 'Costa Rica', 'code' => 'CR', 'telephonecode' => '+ 506','continent_id' => 4],
        ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'telephonecode' => '+ 225','continent_id' => 1],
        ['name' => 'Croatia', 'code' => 'HR', 'telephonecode' => '+ 385','continent_id' => 3],
        ['name' => 'Cuba', 'code' => 'CU', 'telephonecode' => '+ 53','continent_id' => 4],
        ['name' => 'Curaçao', 'code' => 'CW', 'telephonecode' => '+ 599','continent_id' => 2],
        ['name' => 'Cyprus', 'code' => 'CY', 'telephonecode' => '+ 357','continent_id' => 3],
        ['name' => 'Czech Republic', 'code' => 'CZ', 'telephonecode' => '+ 420','continent_id' => 3],
        ['name' => 'Denmark', 'code' => 'DK', 'telephonecode' => '+ 45','continent_id' => 3],
        ['name' => 'Djibouti', 'code' => 'DJ', 'telephonecode' => '+ 253','continent_id' => 1],
        ['name' => 'Dominica', 'code' => 'DM', 'telephonecode' => '+ 1-767','continent_id' => 4],
        ['name' => 'Dominican Republic', 'code' => 'DO', 'telephonecode' => '+ 1-809','continent_id' => 4],
        ['name' => 'Ecuador', 'code' => 'EC', 'telephonecode' => '+ 593','continent_id' => 6],
        ['name' => 'Egypt', 'code' => 'EG', 'telephonecode' => '+ 20','continent_id' => 1],
        ['name' => 'El Salvador', 'code' => 'SV', 'telephonecode' => '+ 503','continent_id' => 4],
        ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'telephonecode' => '+ 240','continent_id' => 1],
        ['name' => 'Eritrea', 'code' => 'ER', 'telephonecode' => '+ 291','continent_id' => 1],
        ['name' => 'Estonia', 'code' => 'EE', 'telephonecode' => '+ 372','continent_id' => 3],
        ['name' => 'Ethiopia', 'code' => 'ET', 'telephonecode' => '+ 251','continent_id' => 1],
        ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'telephonecode' => '+ 500','continent_id' => 6],
        ['name' => 'Faroe Islands', 'code' => 'FO', 'telephonecode' => '+ 298','continent_id' => 3],
        ['name' => 'Fiji', 'code' => 'FJ', 'telephonecode' => '+ 679','continent_id' => 5],
        ['name' => 'Finland', 'code' => 'FI', 'telephonecode' => '+ 358','continent_id' => 3],
        ['name' => 'France', 'code' => 'FR', 'telephonecode' => '+ 33','continent_id' => 3],
        ['name' => 'French Guiana', 'code' => 'GF', 'telephonecode' => '+ 594','continent_id' => 6],
        ['name' => 'French Polynesia', 'code' => 'PF', 'telephonecode' => '+ 689','continent_id' => 5],
        ['name' => 'French Southern Territories', 'code' => 'TF', 'telephonecode' => '+ 262','continent_id' => 5],
        ['name' => 'Gabon', 'code' => 'GA', 'telephonecode' => '+ 241','continent_id' => 1],
        ['name' => 'Gambia', 'code' => 'GM', 'telephonecode' => '+ 220','coninent_id' => 1],
        ['name' => 'Georgia', 'code' => 'GE', 'telephonecode' => '+ 995','continent_id' => 3],
        ['name' => 'Germany', 'code' => 'DE', 'telephonecode' => '+ 49','continent_id' => 3],
        ['name' => 'Ghana', 'code' => 'GH', 'telephonecode' => '+ 233','continent_id' => 3],
        ['name' => 'Gibraltar', 'code' => 'GI', 'telephonecode' => '+ 350','continent_id' => 3],
        ['name' => 'Greece', 'code' => 'GR', 'telephonecode' => '+ 30','continent_id' => 3],
        ['name' => 'Greenland', 'code' => 'GL', 'telephonecode' => '+ 299','continent_id' => 4],
        ['name' => 'Grenada', 'code' => 'GD', 'telephonecode' => '+ 1-473','continent_id' => 4],
        ['name' => 'Guadeloupe', 'code' => 'GP', 'telephonecode' => '+ 590','continent_id' => 4],
        ['name' => 'Guam', 'code' => 'GU', 'telephonecode' => '+ 1-671','continent_id' => 2],
        ['name' => 'Guatemala', 'code' => 'GT', 'telephonecode' => '+ 502','contientent_id' => 4],
        ['name' => 'Guernsey', 'code' => 'GG', 'telephonecode' => '+ 44-1481','continent_id' => 3],
        ['name' => 'Guinea', 'code' => 'GN', 'telephonecode' => '+ 224','continent_id' => 1],
        ['name' => 'Guinea-Bissau', 'code' => 'GW', 'telephonecode' => '+ 245','continent_id' => 1],
        ['name' => 'Guyana', 'code' => 'GY', 'telephonecode' => '+ 592','continent_id' => 6],
        ['name' => 'Haiti', 'code' => 'HT', 'telephonecode' => '+ 509','continent_id' => 4],
        ['name' => 'Heard Island and McDonald Islands', 'code' => 'HM', 'telephonecode' => '+ 672','continent_id' => 5],
        ['name' => 'Honduras', 'code' => 'HN', 'telephonecode' => '+ 504','continent_id' => 4],
        ['name' => 'Hong Kong', 'code' => 'HK', 'telephonecode' => '+ 852','contient_id' => 2],
        ['name' => 'Hungary', 'code' => 'HU', 'telephonecode' => '+ 36','continent_id' => 3],
        ['name' => 'Iceland', 'code' => 'IS', 'telephonecode' => '+ 354','contienent_id' => 3],
        ['name' => 'India', 'code' => 'IN', 'telephonecode' => '+ 91','continent_id' => 2],
        ['name' => 'Indonesia', 'code' => 'ID', 'telephonecode' => '+ 62','continent_id' => 2],
        ['name' => 'Iran', 'code' => 'IR', 'telephonecode' => '+ 98','contient_id' => 2],
        ['name' => 'Iraq', 'code' => 'IQ', 'telephonecode' => '+ 964','continent_id' => 2],
        ['name' => 'Ireland', 'code' => 'IE', 'telephonecode' => '+ 353','continent_id' => 3],
        ['name' => 'Isle of Man', 'code' => 'IM', 'telephonecode' => '+ 44-1624','continent_id' => 3],
        ['name' => 'Israel', 'code' => 'IL', 'telephonecode' => '+ 972','continent_id' => 2],
        ['name' => 'Italy', 'code' => 'IT', 'telephonecode' => '+ 39','continent_id' => 3],
        ['name' => 'Jamaica', 'code' => 'JM', 'telephonecode' => '+ 1-876','continent_id' => 4],
        ['name' => 'Japan', 'code' => 'JP', 'telephonecode' => '+ 81','continent_id' => 2],
        ['name' => 'Jersey', 'code' => 'JE', 'telephonecode' => '+ 44-1534','continent_id' => 3],
        ['name' => 'Jordan', 'code' => 'JO', 'telephonecode' => '+ 962','continent_id' => 2],
        ['name' => 'Kazakhstan', 'code' => 'KZ', 'telephonecode' => '+ 7','continent_id' => 2],
        ['name' => 'Kenya', 'code' => 'KE', 'telephonecode' => '+ 254','contient_id' => 1],
        ['name' => 'Kiribati', 'code' => 'KI', 'telephonecode' => '+ 686','continent_id' => 5],
        ['name' => 'Kuwait', 'code' => 'KW', 'telephonecode' => '+ 965','continent_id' => 2],
        ['name' => 'Kyrgyzstan', 'code' => 'KG', 'telephonecode' => '+ 996','contient_id' => 2],
        ['name' => 'Laos', 'code' => 'LA', 'telephonecode' => '+ 856','continent_id' => 2],
        ['name' => 'Latvia', 'code' => 'LV', 'telephonecode' => '+ 371','contient_id' => 3],
        ['name' => 'Lebanon', 'code' => 'LB', 'telephonecode' => '+ 961','continent_id' => 3],
        ['name' => 'Lesotho', 'code' => 'LS', 'telephonecode' => '+ 266','contient_id' => 1],
        ['name' => 'Liberia', 'code' => 'LR', 'telephonecode' => '+ 231','continent_id' => 1],
        ['name' => 'Libya', 'code' => 'LY', 'telephonecode' => '+ 218','continent_id' => 2],
        ['name' => 'Liechtenstein', 'code' => 'LI', 'telephonecode' => '+ 423','continent_id' => 3],
        ['name' => 'Lithuania', 'code' => 'LT', 'telephonecode' => '+ 370','continent_id' => 3],
        ['name' => 'Luxembourg', 'code' => 'LU', 'telephonecode' => '+ 352','continent_id' => 3],
        ['name' => 'Macao', 'code' => 'MO', 'telephonecode' => '+ 853','continent_id' => 2],
        ['name' => 'Macedonia', 'code' => 'MK', 'telephonecode' => '+ 389','continent_id' => 3],
        ['name' => 'Madagascar', 'code' => 'MG', 'telephonecode' => '+ 261','continent_id' => 1],
        ['name' => 'Malawi', 'code' => 'MW', 'telephonecode' => '+ 265','continent_id' => 1],
        ['name' => 'Malaysia', 'code' => 'MY', 'telephonecode' => '+ 60','continent_id' => 2],
        ['name' => 'Maldives', 'code' => 'MV', 'telephonecode' => '+ 960','continent_id' => 2],
        ['name' => 'Mali', 'code' => 'ML', 'telephonecode' => '+ 223','continent_id' => 1],
        ['name' => 'Malta', 'code' => 'MT', 'telephonecode' => '+ 356','continent_id' => 3],
        ['name' => 'Marshall Islands', 'code' => 'MH', 'telephonecode' => '+ 692','continent_id' => 5],
        ['name' => 'Martinique', 'code' => 'MQ', 'telephonecode' => '+ 596','continent_id' => 4],
        ['name' => 'Mauritania', 'code' => 'MR', 'telephonecode' => '+ 222','contient_id' => 1],
        ['name' => 'Mauritius', 'code' => 'MU', 'telephonecode' => '+ 230','continent_id' => 1],
        ['name' => 'Mayotte', 'code' => 'YT', 'telephonecode' => '+ 262','continent_id' => 1],
        ['name' => 'Mexico', 'code' => 'MX', 'telephonecode' => '+ 52','continent_id' => 4],
        ['name' => 'Micronesia,', 'code' => 'FM', 'telephonecode' => '+ 691','continent_id' => 5],
        ['name' => 'Moldova', 'code' => 'MD', 'telephonecode' => '+ 373','continent_id' => 3],
        ['name' => 'Monaco', 'code' => 'MC', 'telephonecode' => '+ 377','continent_id' => 3],
        ['name' => 'Mongolia', 'code' => 'MN', 'telephonecode' => '+ 976','continent_id' => 2],
        ['name' => 'Montenegro', 'code' => 'ME', 'telephonecode' => '+ 382','continent_id' => 3],
        ['name' => 'Montserrat', 'code' => 'MS', 'telephonecode' => '+ 1-664','continent_id' => 4],
        ['name' => 'Morocco', 'code' => 'MA', 'telephonecode' => '+ 212','continent_id' => 1],
        ['name' => 'Mozambique', 'code' => 'MZ', 'telephonecode' => '+ 258','continent_id' => 1],
        ['name' => 'Myanmar', 'code' => 'MM', 'telephonecode' => '+ 95','continent_id' => 2],
        ['name' => 'Namibia', 'code' => 'NA', 'telephonecode' => '+ 264','continent_id' => 1],
        ['name' => 'Nauru', 'code' => 'NR', 'telephonecode' => '+ 674','continent_id' => 5],
        ['name' => 'Nepal', 'code' => 'NP', 'telephonecode' => '+ 977','continent_id' => 2],
        ['name' => 'Netherlands', 'code' => 'NL', 'telephonecode' => '+ 31','continent_id' => 3],
        ['name' => 'New Caledonia', 'code' => 'NC', 'telephonecode' => '+ 687','continent_id' => 5],
        ['name' => 'New Zealand', 'code' => 'NZ', 'telephonecode' => '+ 64','continent_id' => 5],
        ['name' => 'Nicaragua', 'code' => 'NI', 'telephonecode' => '+ 505','continent_id' => 4],
        ['name' => 'Niger', 'code' => 'NE', 'telephonecode' => '+ 227','continent_id' => 1],
        ['name' => 'Nigeria', 'code' => 'NG', 'telephonecode' => '+ 234','continent_id' => 1],
        ['name' => 'Niue', 'code' => 'NU', 'telephonecode' => '+ 683','continent_id' => 5],
        ['name' => 'Norfolk Island', 'code' => 'NF', 'telephonecode' => '+ 672','continent_id' => 5],
        ['name' => 'North Korea', 'code' => 'KP', 'telephonecode' => '+ 850','continent_id' => 2],
        ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'telephonecode' => '+ 1-670','continent_id' => 5],
        ['name' => 'Norway', 'code' => 'NO', 'telephonecode' => '+ 47','continent_id' => 3],
        ['name' => 'Oman', 'code' => 'OM', 'telephonecode' => '+ 968','continent_id' => 2],
        ['name' => 'Pakistan', 'code' => 'PK', 'telephonecode' => '+ 92','continent_id' => 2],
        ['name' => 'Palau', 'code' => 'PW', 'telephonecode' => '+ 680','continent_id' => 5],
        ['name' => 'Palestine', 'code' => 'PS', 'telephonecode' => '+ 970','continent_id' => 2],
        ['name' => 'Panama', 'code' => 'PA', 'telephonecode' => '+ 507','continent_id' => 4],
        ['name' => 'Papua New Guinea', 'code' => 'PG', 'telephonecode' => '+ 675','continent_id' => 5],
        ['name' => 'Paraguay', 'code' => 'PY', 'telephonecode' => '+ 595','continent_id' => 6],
        ['name' => 'Peru', 'code' => 'PE', 'telephonecode' => '+ 51','continent_id' => 6],
        ['name' => 'Philippines', 'code' => 'PH', 'telephonecode' => '+ 63','continent_id' => 2],
        ['name' => 'Pitcairn', 'code' => 'PN', 'telephonecode' => '+ 64','continent_id' => 5],
        ['name' => 'Poland', 'code' => 'PL', 'telephonecode' => '+ 48','continent_id' => 3],
        ['name' => 'Portugal', 'code' => 'PT', 'telephonecode' => '+ 351','continent_id' => 3],
        ['name' => 'Puerto Rico', 'code' => 'PR', 'telephonecode' => '+ 1','continent_id' => 4],
        ['name' => 'Qatar', 'code' => 'QA', 'telephonecode' => '+ 974','continent_id' => 2],
        ['name' => 'Réunion', 'code' => 'RE', 'telephonecode' => '+ 262','continent_id' => 1],
        ['name' => 'Romania', 'code' => 'RO', 'telephonecode' => '+ 40','continent_id' => 3],
        ['name' => 'Russia', 'code' => 'RU', 'telephonecode' => '+ 7','continent_id' => 3],
        ['name' => 'Rwanda', 'code' => 'RW', 'telephonecode' => '+ 250','continent_id' => 1],
        ['name' => 'Saint Barthélemy', 'code' => 'BL', 'telephonecode' => '+ 590','continent_id' => 4],
        ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH', 'telephonecode' => '+ 290','continent_id' => 1],
        ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'telephonecode' => '+ 1-869','continent_id' => 4],
        ['name' => 'Saint Lucia', 'code' => 'LC', 'telephonecode' => '+ 1-758','continent_id' => 4],
        ['name' => 'Saint Martin (French part)', 'code' => 'MF', 'telephonecode' => '+ 590','continent_id' => 4],
        ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'telephonecode' => '+ 508','continent_id' => 4],
        ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'telephonecode' => '+ 1-784','continent_id' => 4],
        ['name' => 'Samoa', 'code' => 'WS', 'telephonecode' => '+ 685','continent_id' => 5],
        ['name' => 'San Marino', 'code' => 'SM', 'telephonecode' => '+ 378','continent_id' => 3],
        ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'telephonecode' => '+ 239','continent_id' => 1],
        ['name' => 'Saudi Arabia', 'code' => 'SA', 'telephonecode' => '+ 966','continent_id' => 1],
        ['name' => 'Senegal', 'code' => 'SN', 'telephonecode' => '+ 221','continent_id' => 1],
        ['name' => 'Serbia', 'code' => 'RS', 'telephonecode' => '+ 381','continent_id' => 3],
        ['name' => 'Seychelles', 'code' => 'SC', 'telephonecode' => '+ 248','continent_id' => 1],
        ['name' => 'Sierra Leone', 'code' => 'SL', 'telephonecode' => '+ 232','continent_id' => 1],
        ['name' => 'Singapore', 'code' => 'SG', 'telephonecode' => '+ 65','continent_id' => 2],
        ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'telephonecode' => '+ 1-721','continent_id' => 4],
        ['name' => 'Slovakia', 'code' => 'SK', 'telephonecode' => '+ 421','continent_id' => 3],
        ['name' => 'Slovenia', 'code' => 'SI', 'telephonecode' => '+ 386','continent_id' => 3],
        ['name' => 'Solomon Islands', 'code' => 'SB', 'telephonecode' => '+ 677','continent_id' => 5],
        ['name' => 'Somalia', 'code' => 'SO', 'telephonecode' => '+ 252','continent_id' => 1],
        ['name' => 'South Africa', 'code' => 'ZA', 'telephonecode' => '+ 27','continent_id' => 1],
        ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'telephonecode' => '+ 500','continent_id' => 1],
        ['name' => 'South Korea', 'code' => 'KR', 'telephonecode' => '+ 82','continent_id' => 2],
        ['name' => 'South Sudan', 'code' => 'SS', 'telephonecode' => '+ 211','continent_id' => 1],
        ['name' => 'Spain', 'code' => 'ES', 'telephonecode' => '+ 34','continent_id' => 3],
        ['name' => 'Sri Lanka', 'code' => 'LK', 'telephonecode' => '+ 94','continent_id' => 2],
        ['name' => 'Sudan', 'code' => 'SD', 'telephonecode' => '+ 249','continent_id' => 1],
        ['name' => 'Suriname', 'code' => 'SR', 'telephonecode' => '+ 597','continent_id' => 6],
        ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ','telephonecode' => '+ 47', 'continent_id' => 3],
        ['name' => 'Swaziland', 'code' => 'SZ', 'telephonecode' => '+ 268','continent_id' => 1],
        ['name' => 'Sweden', 'code' => 'SE', 'telephonecode' => '+ 46','continent_id' => 3],
        ['name' => 'Switzerland', 'code' => 'CH', 'telephonecode' => '+ 41','continent_id' => 3],
        ['name' => 'Syria', 'code' => 'SY', 'telephonecode' => '+ 963','continent_id' => 2],
        ['name' => 'Taiwan', 'code' => 'TW', 'telephonecode' => '+ 886','continent_id' => 2],
        ['name' => 'Tajikistan', 'code' => 'TJ', 'telephonecode' => '+ 992','continent_id' => 2],
        ['name' => 'Tanzania', 'code' => 'TZ', 'telephonecode' => '+ 255','continent_id' => 1],
        ['name' => 'Thailand', 'code' => 'TH', 'telephonecode' => '+ 66','continent_id' => 2],
        ['name' => 'Timor-Leste', 'code' => 'TL', 'telephonecode' => '+ 670','continent_id' => 5],
        ['name' => 'Togo', 'code' => 'TG', 'telephonecode' => '+ 228','continent_id' => 1],
        ['name' => 'Tokelau', 'code' => 'TK', 'telephonecode' => '+ 690','continent_id' => 5],
        ['name' => 'Tonga', 'code' => 'TO', 'telephonecode' => '+ 676','continent_id' => 5],
        ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'telephonecode' => '+ 1-868','continent_id' => 4],
        ['name' => 'Tunisia', 'code' => 'TN', 'telephonecode' => '+ 216','continent_id' => 1],
        ['name' => 'Turkey', 'code' => 'TR', 'telephonecode' => '+ 90','continent_id' => 1],
        ['name' => 'Turkmenistan', 'code' => 'TM', 'telephonecode' => '+ 993','continent_id' => 2],
        ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'telephonecode' => '+ 1-649','continent_id' => 4],
        ['name' => 'Tuvalu', 'code' => 'TV', 'telephonecode' => '+ 688','continent_id' => 5],
        ['name' => 'Uganda', 'code' => 'UG', 'telephonecode' => '+ 256','continent_id' => 1],
        ['name' => 'Ukraine', 'code' => 'UA', 'telephonecode' => '+ 380','continent_id' => 3],
        ['name' => 'United Arab Emirates', 'code' => 'AE', 'telephonecode' => '+ 971','continent_id' => 2],
        ['name' => 'United Kingdom', 'code' => 'GB', 'telephonecode' => '+ 44','continent_id' => 3],
        ['name' => 'United States', 'code' => 'US', 'telephonecode' => '+ 1','continent_id' => 4],
        ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'telephonecode' => '+ 246', 'continent_id' => 4],
        ['name' => 'US Virgin Islands', 'code' => 'VI', 'telephonecode' => '+ 93','continent_id' => 4],
        ['name' => 'Uruguay', 'code' => 'UY', 'telephonecode' => '+ 598','continent_id' => 6],
        ['name' => 'Uzbekistan', 'code' => 'UZ', 'telephonecode' => '+ 998','continent_id' => 2],
        ['name' => 'Vanuatu', 'code' => 'VU', 'telephonecode' => '+ 678','continent_id' => 5],
        ['name' => 'Vatican City', 'code' => 'VA', 'telephonecode' => '+ 379','continent_id' => 3],
        ['name' => 'Venezuela', 'code' => 'VE', 'telephonecode' => '+ 58','continent_id' => 6],
        ['name' => 'Vietnam', 'code' => 'VN', 'telephonecode' => '+ 84','continent_id' => 2],
        ['name' => 'Wallis and Futuna', 'code' => 'WF', 'telephonecode' => '+ 681','continent_id' => 5],
        ['name' => 'Western Sahara', 'code' => 'EH', 'telephonecode' => '+ 212','continent_id' => 1],
        ['name' => 'Yemen', 'code' => 'YE', 'telephonecode' => '+ 967','continent_id' => 2],
        ['name' => 'Zambia', 'code' => 'ZM', 'telephonecode' => '+ 260','continent_id' => 1],
        ['name' => 'Zimbabwe', 'code' => 'ZW', 'telephonecode' => '+ 263','continent_id' => 1],
    ];

    DB::table('countries')->insert($countries); 
    
    }
}
