<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    DB::table('countries')->truncate(); 

    $countries = [
        ['name' => 'Afghanistan', 'code' => 'AF', 'continent_id' =>  2],
        ['name' => 'Åland Islands', 'code' => 'AX', 'continent_id' => 3],
        ['name' => 'Albania', 'code' => 'AL', 'continent_id' => 3],
        ['name' => 'Algeria', 'code' => 'DZ', 'continent_id' => 1],
        ['name' => 'American Samoa', 'code' => 'AS', 'continent_id' => 5],
        ['name' => 'Andorra', 'code' => 'AD', 'continent_id' => 3],
        ['name' => 'Angola', 'code' => 'AO', 'continent_id' => 1],
        ['name' => 'Anguilla', 'code' => 'AI', 'continent_id' => 4],
        ['name' => 'Antarctica', 'code' => 'AQ', 'continent_id' => 5],
        ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'continent_id' => 4],
        ['name' => 'Argentina', 'code' => 'AR', 'continent_id' => 6],
        ['name' => 'Armenia', 'code' => 'AM', 'continent_id' => 2],
        ['name' => 'Aruba', 'code' => 'AW', 'continent_id' => 6],
        ['name' => 'Australia', 'code' => 'AU', 'continent_id' => 5],
        ['name' => 'Austria', 'code' => 'AT', 'continent_id' => 3],
        ['name' => 'Azerbaijan', 'code' => 'AZ', 'continent_id' => 3],
        ['name' => 'Bahamas', 'code' => 'BS', 'continent_id' => 4],
        ['name' => 'Bahrain', 'code' => 'BH', 'continent_id' => 2],
        ['name' => 'Bangladesh', 'code' => 'BD', 'continent_id' => 2],
        ['name' => 'Barbados', 'code' => 'BB', 'continent_id' => 4],
        ['name' => 'Belarus', 'code' => 'BY', 'contient_id' => 3],
        ['name' => 'Belgium', 'code' => 'BE', 'continent_id' => 3],
        ['name' => 'Belize', 'code' => 'BZ', 'continent_id' => 4],
        ['name' => 'Benin', 'code' => 'BJ', 'continent_id' => 1],
        ['name' => 'Bermuda', 'code' => 'BM', 'continent_id' => 4],
        ['name' => 'Bhutan', 'code' => 'BT', 'continent_id' => 2],
        ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO', 'continent_id' => 6],
        ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'continent_id' => 6],
        ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'continent_id' => 3],
        ['name' => 'Botswana', 'code' => 'BW', 'continent_id' => 1],
        ['name' => 'Bouvet Island', 'code' => 'BV', 'continent_id' => 3],
        ['name' => 'Brazil', 'code' => 'BR', 'continent_id' => 6],
        ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'continent_id' => 2],
        ['name' => 'Brunei Darussalam', 'code' => 'BN', 'continent_id' => 2],
        ['name' => 'Bulgaria', 'code' => 'BG', 'continent_id' => 3],
        ['name' => 'Burkina Faso', 'code' => 'BF', 'continent_id' => 1],
        ['name' => 'Burundi', 'code' => 'BI', 'continent_id' => 1],
        ['name' => 'Cambodia', 'code' => 'KH', 'continent_id' => 1],
        ['name' => 'Cameroon', 'code' => 'CM', 'continent_id' => 1],
        ['name' => 'Canada', 'code' => 'CA', 'continent_id' => 4],
        ['name' => 'Cape Verde', 'code' => 'CV', 'continent_id' => 1],
        ['name' => 'Cayman Islands', 'code' => 'KY', 'continent_id' => 4],
        ['name' => 'Central African Republic', 'code' => 'CF', 'continent_id' => 1],
        ['name' => 'Chad', 'code' => 'TD', 'continent_id' => 1],
        ['name' => 'Chile', 'code' => 'CL', 'continent_id' => 6],
        ['name' => 'China', 'code' => 'CN', 'continent_id' => 2],
        ['name' => 'Christmas Island', 'code' => 'CX', 'continent_id' => 5],
        ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'continent_id' => 5],
        ['name' => 'Colombia', 'code' => 'CO', 'continent_id' => 6],
        ['name' => 'Comoros', 'code' => 'KM', 'continent_id' => 1],
        ['name' => 'Congo', 'code' => 'CG', 'continent_id' => 1],
        ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD', 'continent_id' => 1],
        ['name' => 'Cook Islands', 'code' => 'CK', 'continent_id' => 5],
        ['name' => 'Costa Rica', 'code' => 'CR', 'continent_id' => 4],
        ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'continent_id' => 1],
        ['name' => 'Croatia', 'code' => 'HR', 'continent_id' => 3],
        ['name' => 'Cuba', 'code' => 'CU', 'continent_id' => 4],
        ['name' => 'Curaçao', 'code' => 'CW', 'continent_id' => 2],
        ['name' => 'Cyprus', 'code' => 'CY', 'continent_id' => 3],
        ['name' => 'Czech Republic', 'code' => 'CZ', 'continent_id' => 3],
        ['name' => 'Denmark', 'code' => 'DK', 'continent_id' => 3],
        ['name' => 'Djibouti', 'code' => 'DJ', 'continent_id' => 1],
        ['name' => 'Dominica', 'code' => 'DM', 'continent_id' => 4],
        ['name' => 'Dominican Republic', 'code' => 'DO', 'continent_id' => 4],
        ['name' => 'Ecuador', 'code' => 'EC', 'continent_id' => 6],
        ['name' => 'Egypt', 'code' => 'EG', 'continent_id' => 1],
        ['name' => 'El Salvador', 'code' => 'SV', 'continent_id' => 4],
        ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'continent_id' => 1],
        ['name' => 'Eritrea', 'code' => 'ER', 'continent_id' => 1],
        ['name' => 'Estonia', 'code' => 'EE', 'continent_id' => 3],
        ['name' => 'Ethiopia', 'code' => 'ET', 'continent_id' => 1],
        ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'continent_id' => 6],
        ['name' => 'Faroe Islands', 'code' => 'FO', 'continent_id' => 3],
        ['name' => 'Fiji', 'code' => 'FJ', 'continent_id' => 5],
        ['name' => 'Finland', 'code' => 'FI', 'continent_id' => 3],
        ['name' => 'France', 'code' => 'FR', 'continent_id' => 3],
        ['name' => 'French Guiana', 'code' => 'GF', 'continent_id' => 6],
        ['name' => 'French Polynesia', 'code' => 'PF', 'continent_id' => 5],
        ['name' => 'French Southern Territories', 'code' => 'TF', 'continent_id' => 5],
        ['name' => 'Gabon', 'code' => 'GA', 'continent_id' => 1],
        ['name' => 'Gambia', 'code' => 'GM', 'coninent_id' => 1],
        ['name' => 'Georgia', 'code' => 'GE', 'continent_id' => 3],
        ['name' => 'Germany', 'code' => 'DE', 'continent_id' => 3],
        ['name' => 'Ghana', 'code' => 'GH', 'continent_id' => 3],
        ['name' => 'Gibraltar', 'code' => 'GI', 'continent_id' => 3],
        ['name' => 'Greece', 'code' => 'GR', 'continent_id' => 3],
        ['name' => 'Greenland', 'code' => 'GL', 'continent_id' => 4],
        ['name' => 'Grenada', 'code' => 'GD', 'continent_id' => 4],
        ['name' => 'Guadeloupe', 'code' => 'GP', 'continent_id' => 4],
        ['name' => 'Guam', 'code' => 'GU', 'continent_id' => 2],
        ['name' => 'Guatemala', 'code' => 'GT', 'contientent_id' => 4],
        ['name' => 'Guernsey', 'code' => 'GG', 'continent_id' => 3],
        ['name' => 'Guinea', 'code' => 'GN', 'continent_id' => 1],
        ['name' => 'Guinea-Bissau', 'code' => 'GW', 'continent_id' => 1],
        ['name' => 'Guyana', 'code' => 'GY', 'continent_id' => 6],
        ['name' => 'Haiti', 'code' => 'HT', 'continent_id' => 4],
        ['name' => 'Heard Island and McDonald Islands', 'code' => 'HM', 'continent_id' => 5],
        ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'continent_id' => 3],
        ['name' => 'Honduras', 'code' => 'HN', 'continent_id' => 4],
        ['name' => 'Hong Kong', 'code' => 'HK', 'contient_id' => 2],
        ['name' => 'Hungary', 'code' => 'HU', 'continent_id' => 3],
        ['name' => 'Iceland', 'code' => 'IS', 'contienent_id' => 3],
        ['name' => 'India', 'code' => 'IN', 'continent_id' => 2],
        ['name' => 'Indonesia', 'code' => 'ID', 'continent_id' => 2],
        ['name' => 'Iran', 'code' => 'IR', 'contient_id' => 2],
        ['name' => 'Iraq', 'code' => 'IQ', 'continent_id' => 2],
        ['name' => 'Ireland', 'code' => 'IE', 'continent_id' => 3],
        ['name' => 'Isle of Man', 'code' => 'IM', 'continent_id' => 3],
        ['name' => 'Israel', 'code' => 'IL', 'continent_id' => 2],
        ['name' => 'Italy', 'code' => 'IT', 'continent_id' => 3],
        ['name' => 'Jamaica', 'code' => 'JM', 'continent_id' => 4],
        ['name' => 'Japan', 'code' => 'JP', 'continent_id' => 2],
        ['name' => 'Jersey', 'code' => 'JE', 'continent_id' => 3],
        ['name' => 'Jordan', 'code' => 'JO', 'continent_id' => 2],
        ['name' => 'Kazakhstan', 'code' => 'KZ', 'continent_id' => 2],
        ['name' => 'Kenya', 'code' => 'KE', 'contient_id' => 1],
        ['name' => 'Kiribati', 'code' => 'KI', 'continent_id' => 5],
        ['name' => 'Kuwait', 'code' => 'KW', 'continent_id' => 2],
        ['name' => 'Kyrgyzstan', 'code' => 'KG', 'contient_id' => 2],
        ['name' => 'Laos', 'code' => 'LA', 'continent_id' => 2],
        ['name' => 'Latvia', 'code' => 'LV', 'contient_id' => 3],
        ['name' => 'Lebanon', 'code' => 'LB', 'continent_id' => 3],
        ['name' => 'Lesotho', 'code' => 'LS', 'contient_id' => 1],
        ['name' => 'Liberia', 'code' => 'LR', 'continent_id' => 1],
        ['name' => 'Libya', 'code' => 'LY', 'continent_id' => 2],
        ['name' => 'Liechtenstein', 'code' => 'LI', 'continent_id' => 3],
        ['name' => 'Lithuania', 'code' => 'LT', 'continent_id' => 3],
        ['name' => 'Luxembourg', 'code' => 'LU', 'continent_id' => 3],
        ['name' => 'Macao', 'code' => 'MO', 'continent_id' => 2],
        ['name' => 'Macedonia', 'code' => 'MK', 'continent_id' => 3],
        ['name' => 'Madagascar', 'code' => 'MG', 'continent_id' => 1],
        ['name' => 'Malawi', 'code' => 'MW', 'continent_id' => 1],
        ['name' => 'Malaysia', 'code' => 'MY', 'continent_id' => 2],
        ['name' => 'Maldives', 'code' => 'MV', 'continent_id' => 2],
        ['name' => 'Mali', 'code' => 'ML', 'continent_id' => 1],
        ['name' => 'Malta', 'code' => 'MT', 'continent_id' => 3],
        ['name' => 'Marshall Islands', 'code' => 'MH', 'continent_id' => 5],
        ['name' => 'Martinique', 'code' => 'MQ', 'continent_id' => 4],
        ['name' => 'Mauritania', 'code' => 'MR', 'contient_id' => 1],
        ['name' => 'Mauritius', 'code' => 'MU', 'continent_id' => 1],
        ['name' => 'Mayotte', 'code' => 'YT', 'continent_id' => 1],
        ['name' => 'Mexico', 'code' => 'MX', 'continent_id' => 4],
        ['name' => 'Micronesia,', 'code' => 'FM', 'continent_id' => 5],
        ['name' => 'Moldova', 'code' => 'MD', 'continent_id' => 3],
        ['name' => 'Monaco', 'code' => 'MC', 'continent_id' => 3],
        ['name' => 'Mongolia', 'code' => 'MN', 'continent_id' => 2],
        ['name' => 'Montenegro', 'code' => 'ME', 'continent_id' => 3],
        ['name' => 'Montserrat', 'code' => 'MS', 'continent_id' => 4],
        ['name' => 'Morocco', 'code' => 'MA', 'continent_id' => 1],
        ['name' => 'Mozambique', 'code' => 'MZ', 'continent_id' => 1],
        ['name' => 'Myanmar', 'code' => 'MM', 'continent_id' => 2],
        ['name' => 'Namibia', 'code' => 'NA', 'continent_id' => 1],
        ['name' => 'Nauru', 'code' => 'NR', 'continent_id' => 5],
        ['name' => 'Nepal', 'code' => 'NP', 'continent_id' => 2],
        ['name' => 'Netherlands', 'code' => 'NL', 'continent_id' => 3],
        ['name' => 'New Caledonia', 'code' => 'NC', 'continent_id' => 5],
        ['name' => 'New Zealand', 'code' => 'NZ', 'continent_id' => 5],
        ['name' => 'Nicaragua', 'code' => 'NI', 'continent_id' => 4],
        ['name' => 'Niger', 'code' => 'NE', 'continent_id' => 1],
        ['name' => 'Nigeria', 'code' => 'NG', 'continent_id' => 1],
        ['name' => 'Niue', 'code' => 'NU', 'continent_id' => 5],
        ['name' => 'Norfolk Island', 'code' => 'NF', 'continent_id' => 5],
        ['name' => 'North Korea', 'code' => 'KP', 'continent_id' => 2],
        ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'continent_id' => 5],
        ['name' => 'Norway', 'code' => 'NO', 'continent_id' => 3],
        ['name' => 'Oman', 'code' => 'OM', 'continent_id' => 2],
        ['name' => 'Pakistan', 'code' => 'PK', 'continent_id' => 2],
        ['name' => 'Palau', 'code' => 'PW', 'continent_id' => 5],
        ['name' => 'Palestine', 'code' => 'PS', 'continent_id' => 2],
        ['name' => 'Panama', 'code' => 'PA', 'continent_id' => 4],
        ['name' => 'Papua New Guinea', 'code' => 'PG', 'continent_id' => 5],
        ['name' => 'Paraguay', 'code' => 'PY', 'continent_id' => 6],
        ['name' => 'Peru', 'code' => 'PE', 'continent_id' => 6],
        ['name' => 'Philippines', 'code' => 'PH', 'continent_id' => 2],
        ['name' => 'Pitcairn', 'code' => 'PN', 'continent_id' => 5],
        ['name' => 'Poland', 'code' => 'PL', 'continent_id' => 3],
        ['name' => 'Portugal', 'code' => 'PT', 'continent_id' => 3],
        ['name' => 'Puerto Rico', 'code' => 'PR', 'continent_id' => 4],
        ['name' => 'Qatar', 'code' => 'QA', 'continent_id' => 2],
        ['name' => 'Réunion', 'code' => 'RE', 'continent_id' => 1],
        ['name' => 'Romania', 'code' => 'RO', 'continent_id' => 3],
        ['name' => 'Russian Federation', 'code' => 'RU', 'continent_id' => 3],
        ['name' => 'Rwanda', 'code' => 'RW', 'continent_id' => 1],
        ['name' => 'Saint Barthélemy', 'code' => 'BL', 'continent_id' => 4],
        ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH', 'continent_id' => 1],
        ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'continent_id' => 4],
        ['name' => 'Saint Lucia', 'code' => 'LC', 'continent_id' => 4],
        ['name' => 'Saint Martin (French part)', 'code' => 'MF', 'continent_id' => 4],
        ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'continent_id' => 4],
        ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'continent_id' => 4],
        ['name' => 'Samoa', 'code' => 'WS', 'continent_id' => 5],
        ['name' => 'San Marino', 'code' => 'SM', 'continent_id' => 3],
        ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'continent_id' => 1],
        ['name' => 'Saudi Arabia', 'code' => 'SA', 'continent_id' => 1],
        ['name' => 'Senegal', 'code' => 'SN', 'continent_id' => 1],
        ['name' => 'Serbia', 'code' => 'RS', 'continent_id' => 3],
        ['name' => 'Seychelles', 'code' => 'SC', 'continent_id' => 1],
        ['name' => 'Sierra Leone', 'code' => 'SL', 'continent_id' => 1],
        ['name' => 'Singapore', 'code' => 'SG', 'continent_id' => 2],
        ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'continent_id' => 4],
        ['name' => 'Slovakia', 'code' => 'SK', 'continent_id' => 3],
        ['name' => 'Slovenia', 'code' => 'SI', 'continent_id' => 3],
        ['name' => 'Solomon Islands', 'code' => 'SB', 'continent_id' => 5],
        ['name' => 'Somalia', 'code' => 'SO', 'continent_id' => 1],
        ['name' => 'South Africa', 'code' => 'ZA', 'continent_id' => 1],
        ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'continent_id' => 1],
        ['name' => 'South Korea', 'code' => 'KR', 'continent_id' => 2],
        ['name' => 'South Sudan', 'code' => 'SS', 'continent_id' => 1],
        ['name' => 'Spain', 'code' => 'ES', 'continent_id' => 3],
        ['name' => 'Sri Lanka', 'code' => 'LK', 'continent_id' => 2],
        ['name' => 'Sudan', 'code' => 'SD', 'continent_id' => 1],
        ['name' => 'Suriname', 'code' => 'SR', 'continent_id' => 6],
        ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'continent_id' => 3],
        ['name' => 'Swaziland', 'code' => 'SZ', 'continent_id' => 1],
        ['name' => 'Sweden', 'code' => 'SE', 'continent_id' => 3],
        ['name' => 'Switzerland', 'code' => 'CH', 'continent_id' => 3],
        ['name' => 'Syria', 'code' => 'SY', 'continent_id' => 2],
        ['name' => 'Taiwan', 'code' => 'TW', 'continent_id' => 2],
        ['name' => 'Tajikistan', 'code' => 'TJ', 'continent_id' => 2],
        ['name' => 'Tanzania', 'code' => 'TZ', 'continent_id' => 1],
        ['name' => 'Thailand', 'code' => 'TH', 'continent_id' => 2],
        ['name' => 'Timor-Leste', 'code' => 'TL', 'continent_id' => 5],
        ['name' => 'Togo', 'code' => 'TG', 'continent_id' => 1],
        ['name' => 'Tokelau', 'code' => 'TK', 'continent_id' => 5],
        ['name' => 'Tonga', 'code' => 'TO', 'continent_id' => 5],
        ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'continent_id' => 4],
        ['name' => 'Tunisia', 'code' => 'TN', 'continent_id' => 1],
        ['name' => 'Turkey', 'code' => 'TR', 'continent_id' => 1],
        ['name' => 'Turkmenistan', 'code' => 'TM', 'continent_id' => 2],
        ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'continent_id' => 4],
        ['name' => 'Tuvalu', 'code' => 'TV', 'continent_id' => 5],
        ['name' => 'Uganda', 'code' => 'UG', 'continent_id' => 1],
        ['name' => 'Ukraine', 'code' => 'UA', 'continent_id' => 3],
        ['name' => 'United Arab Emirates', 'code' => 'AE', 'continent_id' => 2],
        ['name' => 'United Kingdom', 'code' => 'GB', 'continent_id' => 3],
        ['name' => 'United States', 'code' => 'US', 'continent_id' => 4],
        ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'continent_id' => 4],
        ['name' => 'Uruguay', 'code' => 'UY', 'continent_id' => 6],
        ['name' => 'Uzbekistan', 'code' => 'UZ', 'continent_id' => 2],
        ['name' => 'Vanuatu', 'code' => 'VU', 'continent_id' => 5],
        ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE', 'continent_id' => 6],
        ['name' => 'Vietnam', 'code' => 'VN', 'continent_id' => 2],
        ['name' => 'Virgin Islands, British', 'code' => 'VG', 'continent_id' => 4],
        ['name' => 'Virgin Islands, U.S.', 'code' => 'VI', 'continent_id' => 4],
        ['name' => 'Wallis and Futuna', 'code' => 'WF', 'continent_id' => 5],
        ['name' => 'Western Sahara', 'code' => 'EH', 'continent_id' => 1],
        ['name' => 'Yemen', 'code' => 'YE', 'continent_id' => 2],
        ['name' => 'Zambia', 'code' => 'ZM', 'continent_id' => 1],
        ['name' => 'Zimbabwe', 'code' => 'ZW', 'continent_id' => 1],
    ];

    DB::table('countries')->insert($countries); 
    
    }
}
